---
- name: Execute selected tasks
  hosts: all
  become: yes
  vars:
    tasks: "{{ tasks.split(',') if tasks is defined else [] }}"
  tasks:
    - include_role:
        name: logrotation
      when: "'logrotation' in tasks"
      tags: logrotation

    - include_role:
        name: docker
      when: "'docker' in tasks"
      tags: docker

    - include_role:
        name: users
      when: "'users' in tasks"
      tags: users

    # Add more tasks here...